### ISSUE TITLE
Add docstrings to functions

### ISSUE THREAD

**Issue by iansan5653** [iansan5653/open-mcr#21]
All functions should be well documented

**Comment by aaftab622** [comment]
Can I fix this issue?

**Comment by aaftab622** [comment]
Can I write docstring for function?

**Comment by iansan5653** [comment]
Sure! Feel free to open a pull request and I'll review it

**Comment by aaftab622** [comment]
As I saw all the python files, There was already docstring added.

**Comment by iansan5653** [comment]
Yeah, docstring coverage actually isn't too bad. I didn't realize that.
