### ISSUE TITLE
Couldn't find document cornors.

### ISSUE THREAD

**Issue by Asifislam110** [iansan5653/open-mcr#24]
Hi iansan,
 i am using below sheet as input but giving error couldn't find document corners.
![omrans](https://user-images.githubusercontent.com/9161848/69904077-efbe5480-13c3-11ea-9632-b0f461f800ae.png)

**Comment by iansan5653** [comment]
@Asifislam110 thanks for the report. I will work on this soon.

**Comment by iansan5653** [comment]
The issue was caused by the image being too low-resolution, so the noise removal filter was destroying too much data. I was able to fix the issue by making the filter more adaptive to image sizes. Keep an eye out for a new release this week with the problem resolved. Thanks again for reporting!
