### ISSUE TITLE
Add original filenames to results.csv

### ISSUE THREAD

**Issue by iansan5653** [iansan5653/open-mcr#28]
This will help in finding the original file if needed to verify results.

**Comment by aaftab622** [comment]
Can I fix this issue?

**Comment by iansan5653** [comment]
Sure! Feel free to open a pull request and I'll review it

**Comment by aaftab622** [comment]
Can you please explain exactly What I have to do?

**Comment by iansan5653** [comment]
Hey @aaftab622, sorry for the delay in responding. Would you still like to work on this? If so I'll explain in more detail and show you where the relevant code is.

**Comment by gajendhir** [comment]
Hi! I have done this...

updated to class Field in **grid_info.py** to include _IMAGE_FILE_
```
class Field(enum.Enum):
    IMAGE_FILE = enum.auto()
    FIRST_NAME = enum.auto()
    TEST_FORM_CODE = enum.auto()
    STUDENT_ID = enum.auto()
    COURSE_ID = enum.auto()
```

and, updated **main.py** to save image_name to field_data, before the _answers_result.add_
```
            for field in form_variant.fields.keys():
                field_value = grid_r.read_field_as_string(field, grid, threshold, form_variant, field_fill_percents[field])
                if field_value is not None:
                    field_data[field] = field_value
            field_data[grid_i.Field.IMAGE_FILE] = image_path.name
            answers_results.add(field_data, answers)

``` 

on a personal note - Ian Sanders you have an excellent solution here, very helpful.

Thanks

**Comment by iansan5653** [comment]
Hi @gajendhir, thanks - this looks good. Could you open a pull request for this? That way you will be credited in the repository history.

If you're not familiar with pull requests, here's a pretty good guide on how it works - https://opensource.guide/how-to-contribute/#opening-a-pull-request

**Comment by gajendhir** [comment]
I shall try to open a pull request - it will be my first time.
