### ISSUE TITLE
does not work on 150questions

### ISSUE THREAD

**Issue by a-pour** [iansan5653/open-mcr#33]
it does not work on 150questions
the error is:
error:<field.Lnastname:1>

**Comment by iansan5653** [comment]
Hello @a-pour, thanks for the report. Can you provide more details? If possible, the image of the sheet that's causing the error would be really helpful. Also the settings you are using.

**Comment by iansan5653** [comment]
Hi again @a-pour  - I just released [OpenMCR 1.0.1](https://github.com/iansan5653/open-mcr/releases/tag/v1.0.1) which fixes this issue. Sorry for the delay in resolving this. Please download and install and let me know if you run into any more problems.
