### ISSUE TITLE
150 Sheet Answers

### ISSUE THREAD

**Issue by LamassuSys** [iansan5653/open-mcr#34]
The script does not process the sheet with 150 questions! It always gives an error :
Error : <Field.LAST_NAME: 1>.
please note that, I am using an image as an answer sheet with Student ID = 9999999999

**Comment by iansan5653** [comment]
Hi @LamassuSys, thanks for the report. Could you share the images you are using?

**Comment by iansan5653** [comment]
Actually, I am able to reproduce this myself. I will look into it and try to fix in the next couple of days.

**Comment by iansan5653** [comment]
Luckily it was simple to fix - thanks for reporting this! I've just released [OpenMCR 1.0.1](https://github.com/iansan5653/open-mcr/releases/tag/v1.0.1). Please download and install that version and let me know how it goes.

**Comment by LamassuSys** [comment]
Thanks
I will do the test
Did you update the GitHub repo as well?

Best Regards

**Comment by iansan5653** [comment]
Yes, the code change is in commit https://github.com/iansan5653/open-mcr/commit/2490b9bc761431a3c2e4665045d189177de5505d and the updated installation files are at https://github.com/iansan5653/open-mcr/releases/tag/v1.0.1.

**Comment by LamassuSys** [comment]
Many thanks

**Comment by LamassuSys** [comment]
Can you please guide me of how to remove the student last, middle, and
first name from the code?
I would like to do some customization and use the student info area to put
some logo and text.

Thanks

**Comment by iansan5653** [comment]
The definition for the 75-question form is located on line 78 of [grid_info.py](https://github.com/iansan5653/open-mcr/blob/2490b9bc761431a3c2e4665045d189177de5505d/code/grid_info.py#L78). I think if you just remove or comment out the lines for first/last/middle name (lines 80-85) it should give the results you want.

**Comment by LamassuSys** [comment]
Perfect 
Many thanks

**Comment by LamassuSys** [comment]
The error has vanished, BUT the results are not accurate. Can you please check the following input sheets If there is anything’s wrong with it

Best

**Comment by LamassuSys** [comment]
Hey Ian
Sorry, just ignore my last email! I figured it out the issue and fixed it.
There is one more thing, by using scanner, the produced images give wrong
results. It looks like, the results shifted one or two positions

If you don’t mind, I will send you the scanned images

Much appreciate your help and support

Best regards

**Comment by LamassuSys** [comment]
Hey
Sorry to bother you,
Is there a way to do the following:
1: changed the student information order, I.e.
  First Name, Middle Name, Last Name
2: export table in other languages such as Arabic
3- control the number of questions other than 75 or 150
4- include True, False questions 

Thanks

**Comment by iansan5653** [comment]
Hello,

Regarding the results being shifted, it may be that the modifications you put on the sheet are tricking the alignment process. Can you send me the scanned images? I think you may need to send a link as an attachment may not appear in GitHub comments.

For the other requests:
1. The only way to do this would be to create a whole new sheet and register it with the software. I don't think there's an easy way.
2. I think the only way to achieve this would be to modify the exported table after generating it.
3. If you want a number smaller than 150, you can just have exam-takers fill in fewer questions and leave the remaining blank. If you want more than 150, you could have them fill out multiple sheets and process two sets of scans. Otherwise no, changing the number of questions on the sheet isn't supported.
4. For true/false, you could just use A/B answers.

**Comment by LamassuSys** [comment]
Many thanks

**Comment by LamassuSys** [comment]
Hi Ian
Hope doing well,
I have some issues with these images as the results are not correct 
Could you please look at them and give me your feedback 
Thanks

**Comment by iansan5653** [comment]
Hello, I cannot see email attachments in the GitHub comments. Could you please upload them somewhere and send a link?

**Comment by LamassuSys** [comment]
Hi Ian
I figured it out the issue and fixed 
Thanks

**Comment by LamassuSys** [comment]
Hi Ian
I have some issues with software as it doesn’t extract correct information
from some of scanned images. I uploaded these images at the GitHub. Will
you please look at the and give me your feedback

Thanks

Ammar
