### ISSUE TITLE
Add a command line interface

### ISSUE THREAD

**Issue by iansan5653** [iansan5653/open-mcr#42]
A CLI would be very useful for debugging and when users want to do bulk processing. The CLI should accept all of the UI inputs as arguments and skip the UI prompt.

CLI design guidelines: https://clig.dev/

The UI currently looks like this: 
![image](https://user-images.githubusercontent.com/2294248/140000311-5a125658-0798-41a3-8904-d1c781e2a4c6.png)

For each input, there would need to be a command line option (ie, `--output-path = ../output`).

**Comment by N1m6** [comment]
Can i tackle this one?
I have some questions. How do you see invoking cli? Should changes be made to main.py or should call to new file be added to init.py?
Ready to start when you share the details.

**Comment by iansan5653** [comment]
Sure, you can definitely tackle this! Fair warning - I marked it as a `good first issue` because it doesn't require much familiarity with the codebase, but it still may be a fair bit of work. If you're up for it though, I think this would be an extremely useful feature.

---

As far as invoking it - I think maybe some restructuring will be needed. We have `main.py` as a single entry-point but now there would be two entry points, so maybe something like `main-gui.py` and `main-cli.py`? Most of the logic that is in `main.py` now would be shared between both entry points (pretty much everything below line 37 except the progress output\*), so it would need to be extracted to some function somewhere and imported into both files.

I honestly have not built a CLI with Python before, so I'm not sure what the standard is here. If you have any experience with it or want to do a little research, I'd trust your opinion.

\* The progress output is a bit of a sticking point since it's mixed into the main logic - most of the UI interaction is just grabbing static values but this one is actually sending data back to the UI. The code in `main.py` interacts with a `ProgressTrackerWidget` class. We could rename this to `UiProgressTracker`, make it extend a new base `ProgressTracker` abstract class, and add a new `CliProgressTracker` implementation. Then make the new main method accept any `ProgressTracker` instance. I know that's somewhat complicated so let me know if you want more details on that.

One last note - currently we distribute the tool using an EXE installer, but I think we don't need to worry about all that for the CLI. If a user is technically comfortable enough to use a command line, I think they can also handle installing Python and downloading the source code. So in other words, don't worry about receiving arguments from the .exe file.

Please don't hesitate to ask if you have any questions!

**Comment by N1m6** [comment]
I don't have much of experience with developing python cli, but did some research. A standard here is to build a package and define entry point there. So when pip installs package it makes system suitable shortcut to entry point. After that cli might be called from any directory as normal command. However your project is distributed by nsis and pyinstaller as i see. If cli is supposed to be only for very advanced user, it can be invoked from source code and calling either `code/main.py` or `code/cli.py`. There is also an option to try recreate logic for establishing entry point shortcut, but it seems to me like a lot of work with little impact. User still would be required to run a script to create a shortcut.

I think implementing `code/cli.py` that will be called from source is good enough to get it up and running. It wouldn't be user-friendly, but could be easily refactored later. It will share many lines with `main.py` and restructuring could be useful. I don't see the good way to wrap needed functionality, though. Regarding `ProgressTrakingWidget`, it will be simpler to track progress and implement progress bar inside cli logic if this is all the widget is doing.

**Comment by iansan5653** [comment]
Makes sense - I guess for the package/entry point method we'd have to publish the package on PyPI? I'm not opposed to that but you're right - it's probably more work than this issue needs to entail. 

I think let's name the CLI entry point `main.py` and the GUI entry point `main-gui.py`. My reasoning is that if you have the source code, most likely you want to run the CLI and not the GUI, so that makes sense as the primary entry point. The GUI will usually only be run from the packaged EXE file after distributing.

**Comment by N1m6** [comment]
Ok. I made it works with argparse module and tqdm module for progress bar. It looks awfully simular to `main.py` as expected. I haven't came up with idea how to wrap core functionalities elegantly, yet. One way is making big function that takes as first parameter either `MainWindow` or `Namespace` object determines with one it got and change some lines with if statements accordingly. It might look messy.. Is there a way to share code with you in case you want to see what are the difference? Or should i rather make a pull request?

**Comment by iansan5653** [comment]
I think the best way to share the code would be to create some common function that takes all the inputs from either source, like:
```py
def main(
  input_folder: Path,
  output_folder: Path,
  multi_answers_as_f: bool,
  empty_answers_as_g: bool,
  keys_file: tp.Optional[Path],
  arrangement_file: tp.Optional[Path],
  sort_results: bool,
  output_mcta: bool,
  debug_mode_on: bool,
  form_variant: FormVariant,
  progress_tracker: ...)
  ...
```

Of course, `progress_tracker` is the only unknown type. For now, an easy implementation would be to make it take `tp.Optional[ProgressTrackerWidget]` and just not call the methods if the value is `None`. In the future we could add a progress tracking implementation specifically for the CLI.

Please do make a pull request and then I can comment on that.
