### ISSUE TITLE
List of images that are bad answer sheets.

### ISSUE THREAD

**Issue by gajendhir** [iansan5653/open-mcr#59]
I have used the software to check about 200 answer sheets in one go.  The software was unable to handle bad answer sheets . 

So, I had to physically identify and separate the bad answer sheets.

If its okay, I would like to add a feature where the software will generate a separate output file to show the list of images that were ***bad-answer-sheets***. 

*bad answer sheets* are those that do not have the **required corners** - it could be due to...
- bad scans
- dirty / stained pages
- images that are not answer sheets at all
- or any such reason

**Comment by iansan5653** [comment]
Great suggestion - this should be a simple feature to add.
